# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Model Creation

on:
  # push:
  #   branches:
  #     - feature/update-model
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - pca: 2
          # - pca: 3
          - pca: None
          - pca: 5
          - pca: 7
          # - pca: 9
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Decrypt script
        env:
          RH_PASSWORD: ${{ secrets.RH_PASSWORD }}
          SALT: ${{ secrets.SALT }}
        run: |
          python util/decrypt.py encrypted/create_model.py

      - name: Create model
        env:
          PCA: ${{ matrix.pca }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          python encrypted/create_model.py

      # Add step to create visualization after automating model creation
      # Should be able to copy step from visualize.yml
