# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Dev Pipeline

on:
  pull_request:
    branches: [master]

env:
  # RUN_ID is necessary for tests
  RUN_ID: ${{ github.run_id }}
  RH_USERNAME: ${{ secrets.RH_USERNAME }}
  RH_PASSWORD: ${{ secrets.RH_PASSWORD }}
  RH_2FA: ${{ secrets.RH_2FA }}
  IEXCLOUD: ${{ secrets.IEXCLOUD }}
  IEXCLOUD_SANDBOX: ${{ secrets.IEXCLOUD_SANDBOX }}
  STOCKTWITS: ${{ secrets.STOCKTWITS }}
  GLASSNODE: ${{ secrets.GLASSNODE }}
  S3_BUCKET: ${{ secrets.S3_DEV_BUCKET }}
  POLYGON: ${{ secrets.POLYGON }}
  BLS: ${{ secrets.BLS }}
  BINANCE_TESTNET_KEY: ${{ secrets.BINANCE_TESTNET_KEY }}
  BINANCE_TESTNET_SECRET: ${{ secrets.BINANCE_TESTNET_SECRET }}
  KRAKEN_KEY: ${{ secrets.KRAKEN_KEY }}
  KRAKEN_SECRET: ${{ secrets.KRAKEN_SECRET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  TEST: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run all unit tests
        run: coverage run -m pytest -vv -s

      - name: Generate test coverage report
        run: coverage report -m -i --fail-under=95

      - name: Update symbols
        run: python scripts/update_symbols.py

      # - name: Update dividends
      #   run: python scripts/update_dividends.py

      # - name: Update splits
      #   run: python scripts/update_splits.py

      # - name: Update OHLC
      #   run: python scripts/update_ohlc.py

      - name: Update social sentiment
        run: python scripts/update_sentiment.py

      # - name: Update intraday
      #   run: python scripts/update_intraday.py

      - name: Update unemployment
        run: python scripts/update_unrate.py

      - name: Update API
        env:
          SYMBOL: ${{ secrets.SYMBOL }}
        run: python scripts/update_api.py

      - name: Decrypt scripts
        env:
          SALT: ${{ secrets.SALT }}
        run: |
          python util/decrypt.py encrypted/create_model.py
          python util/decrypt.py encrypted/predict_signal.py

      - name: Create model
        run: python encrypted/create_model.py

      - name: Create visualization
        run: python scripts/visualize.py

      - name: Predict signal
        run: python encrypted/predict_signal.py

      - name: Execute order
        run: python scripts/execute_order.py
